/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klmpk5_buah;

/**
 *
 * @author ThinkPad
 */
public class JerukFrame extends javax.swing.JFrame {

    /**
     * Creates new form Jeruk_cialin
     */
    public JerukFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Tnamabuah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TWarna = new javax.swing.JTextField();
        TRasa = new javax.swing.JTextField();
        TBerat = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        RadioTidak = new javax.swing.JRadioButton();
        RadioYa = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Tnamabuah1 = new javax.swing.JTextField();
        Twarna1 = new javax.swing.JTextField();
        Trasa1 = new javax.swing.JTextField();
        TBerat1 = new javax.swing.JTextField();
        THarga1 = new javax.swing.JTextField();
        Tkulit1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        THarga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Baground = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Nama Buah");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 22, -1, -1));

        Tnamabuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnamabuahActionPerformed(evt);
            }
        });
        getContentPane().add(Tnamabuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Warna");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Rasa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(TWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        TRasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRasaActionPerformed(evt);
            }
        });
        getContentPane().add(TRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 150, -1));

        TBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBeratActionPerformed(evt);
            }
        });
        getContentPane().add(TBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 90, -1));

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setAutoscrolls(true);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        btnTampil.setBackground(new java.awt.Color(204, 204, 204));
        btnTampil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTampil.setText("Tampil");
        btnTampil.setAutoscrolls(true);
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });
        getContentPane().add(btnTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        RadioTidak.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup1.add(RadioTidak);
        RadioTidak.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        RadioTidak.setText("Tidak");
        RadioTidak.setBorder(null);
        RadioTidak.setContentAreaFilled(false);
        getContentPane().add(RadioTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        RadioYa.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroup1.add(RadioYa);
        RadioYa.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        RadioYa.setText("Ya");
        RadioYa.setContentAreaFilled(false);
        RadioYa.setFocusPainted(false);
        RadioYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioYaActionPerformed(evt);
            }
        });
        getContentPane().add(RadioYa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Harga per/kg");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Berat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        btnTutup.setBackground(new java.awt.Color(204, 204, 204));
        btnTutup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTutup.setText("Back");
        btnTutup.setAutoscrolls(true);
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(btnTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 339, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Kulit Yang Bisa dimakan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("Nama Buah");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 28, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Warna");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 62, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("Rasa");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 96, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setText("Harga /kg");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setText("Berat");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setText("Kulit Yang Bisa dimakan");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        Tnamabuah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tnamabuah1ActionPerformed(evt);
            }
        });
        jPanel1.add(Tnamabuah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 25, 150, -1));
        jPanel1.add(Twarna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 59, 150, -1));

        Trasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trasa1ActionPerformed(evt);
            }
        });
        jPanel1.add(Trasa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 93, 150, -1));

        TBerat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBerat1ActionPerformed(evt);
            }
        });
        jPanel1.add(TBerat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 110, -1));

        THarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THarga1ActionPerformed(evt);
            }
        });
        jPanel1.add(THarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 180, -1));

        Tkulit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tkulit1ActionPerformed(evt);
            }
        });
        jPanel1.add(Tkulit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 180, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Gram");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 201, 640, 130));

        THarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaActionPerformed(evt);
            }
        });
        getContentPane().add(THarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 150, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Gram");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        Baground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Jeruk.PNG.png"))); // NOI18N
        getContentPane().add(Baground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TRasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRasaActionPerformed

    private void TBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBeratActionPerformed

    private void TnamabuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnamabuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnamabuahActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        Cialin_Jeruk Jerr = new Cialin_Jeruk();
        
        if (Tnamabuah.getText().isEmpty()) {
          Jerr.setnama_buah("Tidak Diketahui");
        } else {
          Jerr.setnama_buah(Tnamabuah.getText());
}
        
        if (TWarna.getText().isEmpty()) {
                Jerr.setWarna("Tidak Diketahui");
            } else {
                Jerr.setWarna(TWarna.getText());
            }
            if (TRasa.getText().isEmpty()) {
                Jerr.setRasa("Tidak Diketahui");
            } else {
                Jerr.setRasa(TRasa.getText());
            }
            if (TBerat.getText().isEmpty()) {
                Jerr.setBerat(0);
            } else {
                Jerr.setBerat(Double.parseDouble(TBerat.getText()));
            }
            if (THarga.getText().isEmpty()) {
                Jerr.setHarga(0);
            } else {
                Jerr.setHarga(Double.parseDouble(THarga.getText()));
            }

        
        
        

        Tnamabuah1.setText(Jerr.getnama_buah());
        Twarna1.setText(Jerr.getWarna());
        Trasa1.setText(Jerr.getRasa());
        THarga1.setText(String.valueOf(Jerr.getHarga()));
        TBerat1.setText(String.valueOf(Jerr.getBerat()));
        
        if (RadioYa.isSelected()) {
            Tkulit1.setText("Ya, Bisa dimakan"); 
        }else if (RadioTidak.isSelected()) {
            Tkulit1.setText("Tidak, Kulit tidak bisa dimakan");
            
        }else{
            Tkulit1.setText("Tidak Diketahui");
        }

        
            
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        Tnamabuah.setText(null);
        TWarna.setText(null);
        TRasa.setText(null);
        TBerat.setText(null);
        THarga.setText(null);
        Tnamabuah1.setText(null);
        Twarna1.setText(null);
        Trasa1.setText(null);
        THarga1.setText(null);
        TBerat1.setText(null);
        Tkulit1.setText(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_btnTutupActionPerformed

    private void Tkulit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tkulit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tkulit1ActionPerformed

    private void THarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THarga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THarga1ActionPerformed

    private void TBerat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBerat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBerat1ActionPerformed

    private void Trasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trasa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Trasa1ActionPerformed

    private void Tnamabuah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tnamabuah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tnamabuah1ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void RadioYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioYaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioYaActionPerformed

    private void THargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JerukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JerukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JerukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JerukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JerukFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baground;
    private javax.swing.JRadioButton RadioTidak;
    private javax.swing.JRadioButton RadioYa;
    private javax.swing.JTextField TBerat;
    private javax.swing.JTextField TBerat1;
    private javax.swing.JTextField THarga;
    private javax.swing.JTextField THarga1;
    private javax.swing.JTextField TRasa;
    private javax.swing.JTextField TWarna;
    private javax.swing.JTextField Tkulit1;
    private javax.swing.JTextField Tnamabuah;
    private javax.swing.JTextField Tnamabuah1;
    private javax.swing.JTextField Trasa1;
    private javax.swing.JTextField Twarna1;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTampil;
    private javax.swing.JButton btnTutup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
