/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klmpk5_buah;

/**
 *
 * @author cherly
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tkurma = new javax.swing.JButton();
        tJeruk = new javax.swing.JButton();
        tManggis = new javax.swing.JButton();
        tApel = new javax.swing.JButton();
        tNanas = new javax.swing.JButton();
        tMangga = new javax.swing.JButton();
        tTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu Utama.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        tkurma.setText("fkurma");
        tkurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkurmaActionPerformed(evt);
            }
        });
        getContentPane().add(tkurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 180, 40));

        tJeruk.setText("fjeruk");
        tJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJerukActionPerformed(evt);
            }
        });
        getContentPane().add(tJeruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 180, 40));

        tManggis.setText("fmanggis");
        tManggis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tManggisActionPerformed(evt);
            }
        });
        getContentPane().add(tManggis, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 180, 40));

        tApel.setText("fapel");
        tApel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tApelActionPerformed(evt);
            }
        });
        getContentPane().add(tApel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 170, 40));

        tNanas.setText("fnanas");
        tNanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNanasActionPerformed(evt);
            }
        });
        getContentPane().add(tNanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 180, 40));

        tMangga.setText("fmangga");
        tMangga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tManggaActionPerformed(evt);
            }
        });
        getContentPane().add(tMangga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 180, 40));

        tTutup.setText("TUTUP");
        tTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTutupActionPerformed(evt);
            }
        });
        getContentPane().add(tTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 100, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tManggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tManggaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ManggaFrame().setVisible(true);
    }//GEN-LAST:event_tManggaActionPerformed

    private void tTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTutupActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tTutupActionPerformed

    private void tApelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApelActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tApelActionPerformed

    private void tManggisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tManggisActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ManggisFrame().setVisible(true);
    }//GEN-LAST:event_tManggisActionPerformed

    private void tJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJerukActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new JerukFrame().setVisible(true);
    }//GEN-LAST:event_tJerukActionPerformed

    private void tkurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkurmaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Tonikurmaframe().setVisible(true);
    }//GEN-LAST:event_tkurmaActionPerformed

    private void tNanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNanasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new NanasFrame().setVisible(true);
    }//GEN-LAST:event_tNanasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tApel;
    private javax.swing.JButton tJeruk;
    private javax.swing.JButton tMangga;
    private javax.swing.JButton tManggis;
    private javax.swing.JButton tNanas;
    private javax.swing.JButton tTutup;
    private javax.swing.JButton tkurma;
    // End of variables declaration//GEN-END:variables
}
