/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klmpk5_buah;

import javax.swing.ButtonGroup;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class ManggisFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManggisFrame
     */
    public ManggisFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jNamaBuah1 = new javax.swing.JLabel();
        tNamaBuah1 = new javax.swing.JTextField();
        jWarnaBuah1 = new javax.swing.JLabel();
        tWarnaBuah1 = new javax.swing.JTextField();
        jRasa1 = new javax.swing.JLabel();
        tRasa1 = new javax.swing.JTextField();
        jBerat1 = new javax.swing.JLabel();
        tBerat1 = new javax.swing.JTextField();
        jHarga1 = new javax.swing.JLabel();
        tHarga1 = new javax.swing.JTextField();
        jKulit1 = new javax.swing.JLabel();
        tkulit = new javax.swing.JTextField();
        jNamaBuah = new javax.swing.JLabel();
        tNamaBuah = new javax.swing.JTextField();
        jWarnaBuah = new javax.swing.JLabel();
        tWarnaBuah = new javax.swing.JTextField();
        jRasa = new javax.swing.JLabel();
        tRasa = new javax.swing.JTextField();
        jBerat = new javax.swing.JLabel();
        tBerat = new javax.swing.JTextField();
        jHarga = new javax.swing.JLabel();
        tHarga = new javax.swing.JTextField();
        jKulit = new javax.swing.JLabel();
        jTampilan = new javax.swing.JButton();
        yaRadioButton = new javax.swing.JRadioButton();
        TidakRadioButton2 = new javax.swing.JRadioButton();
        jreset = new javax.swing.JButton();
        ButtonTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("output"));

        jNamaBuah1.setText("Nama Buah ");

        tNamaBuah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaBuah1ActionPerformed(evt);
            }
        });

        jWarnaBuah1.setText("Warna Buah ");

        tWarnaBuah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tWarnaBuah1ActionPerformed(evt);
            }
        });

        jRasa1.setText("Rasa            ");

        tRasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRasa1ActionPerformed(evt);
            }
        });

        jBerat1.setText("Berat           ");

        tBerat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBerat1ActionPerformed(evt);
            }
        });

        jHarga1.setText("Harga per/kg");

        tHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHarga1ActionPerformed(evt);
            }
        });

        jKulit1.setText("Kulit bisa  dimakan");

        tkulit.setAutoscrolls(false);
        tkulit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkulitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNamaBuah1)
                    .addComponent(jWarnaBuah1)
                    .addComponent(jRasa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tWarnaBuah1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(tNamaBuah1)
                    .addComponent(tRasa1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBerat1)
                    .addComponent(jHarga1)
                    .addComponent(jKulit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tHarga1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(tBerat1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tkulit))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNamaBuah1)
                    .addComponent(tNamaBuah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBerat1)
                    .addComponent(tBerat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tWarnaBuah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWarnaBuah1)
                    .addComponent(jHarga1)
                    .addComponent(tHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tRasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRasa1)
                    .addComponent(jKulit1)
                    .addComponent(tkulit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 120));

        jNamaBuah.setText("Nama Buah ");
        getContentPane().add(jNamaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 65, -1));

        tNamaBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaBuahActionPerformed(evt);
            }
        });
        getContentPane().add(tNamaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 210, -1));

        jWarnaBuah.setText("Warna Buah ");
        getContentPane().add(jWarnaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        tWarnaBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tWarnaBuahActionPerformed(evt);
            }
        });
        getContentPane().add(tWarnaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 210, -1));

        jRasa.setText("Rasa            ");
        getContentPane().add(jRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

        tRasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRasaActionPerformed(evt);
            }
        });
        getContentPane().add(tRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, -1));

        jBerat.setText("Berat           ");
        getContentPane().add(jBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, -1));

        tBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBeratActionPerformed(evt);
            }
        });
        getContentPane().add(tBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 210, -1));

        jHarga.setText("Harga per/kg");
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 90, -1));

        tHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHargaActionPerformed(evt);
            }
        });
        getContentPane().add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 180, -1));

        jKulit.setText("Kulit bisa  dimakan");
        getContentPane().add(jKulit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 100, -1));

        jTampilan.setText("Tampil");
        jTampilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTampilanActionPerformed(evt);
            }
        });
        getContentPane().add(jTampilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        yaRadioButton.setText("Ya");
        yaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yaRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        TidakRadioButton2.setText("Tidak");
        TidakRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TidakRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(TidakRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 52, -1));

        jreset.setText("Reset");
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });
        getContentPane().add(jreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        ButtonTutup.setText("Tutup");
        ButtonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTutupActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaBuahActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tNamaBuahActionPerformed

    private void tWarnaBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tWarnaBuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tWarnaBuahActionPerformed

    private void tRasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRasaActionPerformed

    private void tBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBeratActionPerformed

    private void tHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHargaActionPerformed

    private void jTampilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTampilanActionPerformed
        Ichul_Manggis mgs = new Ichul_Manggis();
        
        if (tNamaBuah.getText().isEmpty()){
            mgs.setnama_buah("Tidak diketahui");
        }else {
            mgs.setnama_buah(tNamaBuah.getText());
        }
        if (tWarnaBuah1.getText().isEmpty()){
            mgs.setwarna("Tidak diketahui");
        }else {
            mgs.setwarna(tWarnaBuah1.getText());
        };
        if (tRasa.getText().isEmpty()){
            mgs.setrasa("Tidak diketahui");
        }else {
            mgs.setrasa(tRasa.getText());
        };
        if (tBerat.getText().isEmpty()){
            mgs.setberat(0);
        }else {
            mgs.setberat(Double.parseDouble(tBerat.getText()));
        };
        if (tHarga.getText().isEmpty()){
            mgs.setharga(0);
        }else {
            mgs.setharga(Double.parseDouble(tHarga.getText()));
        };
        
        tNamaBuah1.setText(mgs.getnama_buah());
        tWarnaBuah1.setText(mgs.getwarna());
        tRasa1.setText(mgs.getrasa());
        tBerat1.setText(String.valueOf(mgs.getberat()));
        tHarga1.setText(String.valueOf(mgs.getharga()));
        
        if (yaRadioButton.isSelected()){
            tkulit.setText("Ya, Bisa dimakan");
        }else {
            tkulit.setText("Tidak, Kulit tidak bisa dimakan");
        }
        
    }//GEN-LAST:event_jTampilanActionPerformed

    private void tNamaBuah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaBuah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaBuah1ActionPerformed

    private void tWarnaBuah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tWarnaBuah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tWarnaBuah1ActionPerformed

    private void tRasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRasa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRasa1ActionPerformed

    private void tBerat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBerat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBerat1ActionPerformed

    private void tHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHarga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHarga1ActionPerformed

    private void tkulitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkulitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkulitActionPerformed

    private void yaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaRadioButtonActionPerformed
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(yaRadioButton);
    }//GEN-LAST:event_yaRadioButtonActionPerformed

    private void TidakRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidakRadioButton2ActionPerformed
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(TidakRadioButton2);
    }//GEN-LAST:event_TidakRadioButton2ActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        tNamaBuah.setText(null);
        tWarnaBuah.setText(null);
        tRasa.setText(null);
        tBerat.setText(null);
        tHarga.setText(null);
    }//GEN-LAST:event_jresetActionPerformed

    private void ButtonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManggisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManggisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManggisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManggisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new ManggisFrame().setVisible(true);
            }
        });    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTutup;
    private javax.swing.JRadioButton TidakRadioButton2;
    private javax.swing.JLabel jBerat;
    private javax.swing.JLabel jBerat1;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jHarga1;
    private javax.swing.JLabel jKulit;
    private javax.swing.JLabel jKulit1;
    private javax.swing.JLabel jNamaBuah;
    private javax.swing.JLabel jNamaBuah1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jRasa;
    private javax.swing.JLabel jRasa1;
    private javax.swing.JButton jTampilan;
    private javax.swing.JLabel jWarnaBuah;
    private javax.swing.JLabel jWarnaBuah1;
    private javax.swing.JButton jreset;
    private javax.swing.JTextField tBerat;
    private javax.swing.JTextField tBerat1;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tHarga1;
    private javax.swing.JTextField tNamaBuah;
    private javax.swing.JTextField tNamaBuah1;
    private javax.swing.JTextField tRasa;
    private javax.swing.JTextField tRasa1;
    private javax.swing.JTextField tWarnaBuah;
    private javax.swing.JTextField tWarnaBuah1;
    private javax.swing.JTextField tkulit;
    private javax.swing.JRadioButton yaRadioButton;
    // End of variables declaration//GEN-END:variables
}
