/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klmpk5_buah;

/**
 *
 * @author cherly
 */
public class ManggaFrame extends javax.swing.JFrame {

    public ManggaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tWarna = new javax.swing.JTextField();
        tRasa = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tNB1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tWarna1 = new javax.swing.JTextField();
        tRasa1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tBerat1 = new javax.swing.JTextField();
        tHarga1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tKulit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bReset = new javax.swing.JButton();
        bTampil = new javax.swing.JButton();
        bTutup = new javax.swing.JButton();
        tBerat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radioYa = new javax.swing.JRadioButton();
        radioTidak = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nama Buah");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Warna");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 20));
        getContentPane().add(tNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Rasa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Kulit Bisa Dimakan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 123, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Harga per/kg");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));
        getContentPane().add(tWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, -1));

        tRasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRasaActionPerformed(evt);
            }
        });
        getContentPane().add(tRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, -1));
        getContentPane().add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 160, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nama Buah");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Warna");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        tNB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNB1ActionPerformed(evt);
            }
        });
        jPanel1.add(tNB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Rasa");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel1.add(tWarna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, -1));

        tRasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRasa1ActionPerformed(evt);
            }
        });
        jPanel1.add(tRasa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Berat");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Harga per/kg");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        tBerat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBerat1ActionPerformed(evt);
            }
        });
        jPanel1.add(tBerat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 80, -1));

        tHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHarga1ActionPerformed(evt);
            }
        });
        jPanel1.add(tHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 160, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Kulit Bisa Dimakan");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        tKulit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKulitActionPerformed(evt);
            }
        });
        jPanel1.add(tKulit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 160, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Gram");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/APanel.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 710, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 640, 150));

        bReset.setBackground(new java.awt.Color(0, 102, 0));
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        getContentPane().add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 73, -1));

        bTampil.setBackground(new java.awt.Color(0, 102, 0));
        bTampil.setForeground(new java.awt.Color(255, 255, 255));
        bTampil.setText("Tampil");
        bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTampilActionPerformed(evt);
            }
        });
        getContentPane().add(bTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        bTutup.setBackground(new java.awt.Color(0, 102, 0));
        bTutup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bTutup.setForeground(new java.awt.Color(255, 255, 255));
        bTutup.setText("Back");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });
        getContentPane().add(bTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 90, 30));
        getContentPane().add(tBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Berat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 70, 20));

        buttonGroup2.add(radioYa);
        radioYa.setText("Ya");
        getContentPane().add(radioYa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        buttonGroup2.add(radioTidak);
        radioTidak.setText("Tidak");
        radioTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTidakActionPerformed(evt);
            }
        });
        getContentPane().add(radioTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Gram");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AFrame.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tRasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRasaActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        tNB.setText(null);
        tWarna.setText(null);
        tRasa.setText(null);
        tBerat.setText(null);
        tHarga.setText(null);
        
        buttonGroup2.clearSelection();
        tKulit.setText(null);
        
        tNB1.setText(null);
        tWarna1.setText(null);
        tRasa1.setText(null);
        tBerat1.setText(null);
        tHarga1.setText(null);
    }//GEN-LAST:event_bResetActionPerformed

    private void bTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTampilActionPerformed
        // TODO add your handling code here:
        cherlyMangga mgf = new cherlyMangga();
        
                
        if (tNB.getText().isEmpty()) {
            mgf.setnama_buah("");
        } else {
            mgf.setnama_buah(tNB.getText());
        }
        if (tWarna.getText().isEmpty()) {
            mgf.setwarna("");
        } else {
            mgf.setwarna(tWarna.getText()); 
        }
        if (tRasa.getText().isEmpty()) {
            mgf.setrasa("");
        } else {
            mgf.setrasa(tRasa.getText());
        }
        if (tBerat.getText().isEmpty()) {
            mgf.setberat (0);
        } else {
            mgf.setberat(Double.parseDouble(tBerat.getText()));
        }
        if (tHarga.getText().isEmpty()) {
            mgf.setharga(0);
        } else {
            mgf.setharga(Double.parseDouble(tHarga.getText()));
        }
        
        tNB1.setText(mgf.getnama_buah());
        tWarna1.setText(mgf.getwarna());
        tRasa1.setText(mgf.getrasa());
        tBerat1.setText(String.valueOf(mgf.getberat()));
        tHarga1.setText(String.valueOf(mgf.getharga()));
        
        if (radioYa.isSelected()) {
            tKulit.setText("Bisa dimakan");
        } else if (radioTidak.isSelected()) {
            tKulit.setText("Tidak Bisa Dimakan");
        } else {
            
        }
        
        
        
    }//GEN-LAST:event_bTampilActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_bTutupActionPerformed

    private void radioTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTidakActionPerformed

    private void tKulitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKulitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKulitActionPerformed

    private void tHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHarga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHarga1ActionPerformed

    private void tBerat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBerat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBerat1ActionPerformed

    private void tRasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRasa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRasa1ActionPerformed

    private void tNB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManggaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManggaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManggaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManggaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManggaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTampil;
    private javax.swing.JButton bTutup;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioTidak;
    private javax.swing.JRadioButton radioYa;
    private javax.swing.JTextField tBerat;
    private javax.swing.JTextField tBerat1;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tHarga1;
    private javax.swing.JTextField tKulit;
    private javax.swing.JTextField tNB;
    private javax.swing.JTextField tNB1;
    private javax.swing.JTextField tRasa;
    private javax.swing.JTextField tRasa1;
    private javax.swing.JTextField tWarna;
    private javax.swing.JTextField tWarna1;
    // End of variables declaration//GEN-END:variables

    private cherlyMangga cherlyMangga() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
