/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klmpk5_buah;

/**
 *
 * @author user
 */
public class NanasFrame extends javax.swing.JFrame {

    /**
     * Creates new form NanasFrame
     */
    public NanasFrame() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jNamaBuah1 = new javax.swing.JLabel();
        tNamaBuah2 = new javax.swing.JTextField();
        jWarnaBuah1 = new javax.swing.JLabel();
        tWarna2 = new javax.swing.JTextField();
        jRasa1 = new javax.swing.JLabel();
        tRasa1 = new javax.swing.JTextField();
        jBerat1 = new javax.swing.JLabel();
        tBerat1 = new javax.swing.JTextField();
        jHarga1 = new javax.swing.JLabel();
        tHarga1 = new javax.swing.JTextField();
        jKulit1 = new javax.swing.JLabel();
        tKulit2 = new javax.swing.JTextField();
        jNamaBuah = new javax.swing.JLabel();
        tNamaBuah = new javax.swing.JTextField();
        jWarnaBuah = new javax.swing.JLabel();
        tWarnaBuah = new javax.swing.JTextField();
        jRasa = new javax.swing.JLabel();
        tRasa = new javax.swing.JTextField();
        jBerat = new javax.swing.JLabel();
        tBerat = new javax.swing.JTextField();
        jHarga = new javax.swing.JLabel();
        tHarga = new javax.swing.JTextField();
        jKulit = new javax.swing.JLabel();
        jTampil = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jTutup = new javax.swing.JButton();
        jYa = new javax.swing.JRadioButton();
        jTidak = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel1.setOpaque(false);

        jNamaBuah1.setText("Nama Buah ");

        tNamaBuah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaBuah2ActionPerformed(evt);
            }
        });

        jWarnaBuah1.setText("Warna Buah ");

        tWarna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tWarna2ActionPerformed(evt);
            }
        });

        jRasa1.setText("Rasa");

        tRasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRasa1ActionPerformed(evt);
            }
        });

        jBerat1.setText("Berat");

        tBerat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBerat1ActionPerformed(evt);
            }
        });

        jHarga1.setText("Harga per/Kg");

        tHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHarga1ActionPerformed(evt);
            }
        });

        jKulit1.setText("Kulit Bisa Dimakan");

        tKulit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKulit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jNamaBuah1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(tNamaBuah2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jBerat1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(tBerat1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tRasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jWarnaBuah1)
                        .addGap(6, 6, 6)
                        .addComponent(tWarna2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(143, 143, 143)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jHarga1)
                        .addGap(49, 49, 49)
                        .addComponent(tHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jKulit1)
                        .addGap(23, 23, 23)
                        .addComponent(tKulit2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jNamaBuah1))
                    .addComponent(tNamaBuah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jBerat1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tBerat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jWarnaBuah1))
                    .addComponent(tWarna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jHarga1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(tHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tRasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jKulit1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tKulit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 660, -1));

        jNamaBuah.setText("Nama Buah ");
        getContentPane().add(jNamaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 67, 20));

        tNamaBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaBuahActionPerformed(evt);
            }
        });
        getContentPane().add(tNamaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 151, -1));

        jWarnaBuah.setText("Warna Buah ");
        getContentPane().add(jWarnaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        tWarnaBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tWarnaBuahActionPerformed(evt);
            }
        });
        getContentPane().add(tWarnaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 151, -1));

        jRasa.setText("Rasa");
        getContentPane().add(jRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 67, 22));

        tRasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRasaActionPerformed(evt);
            }
        });
        getContentPane().add(tRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 151, -1));

        jBerat.setText("Berat");
        getContentPane().add(jBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 42, -1));

        tBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBeratActionPerformed(evt);
            }
        });
        getContentPane().add(tBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 151, -1));

        jHarga.setText("Harga per/Kg");
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        tHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHargaActionPerformed(evt);
            }
        });
        getContentPane().add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 151, -1));

        jKulit.setText("Kulit Bisa Dimakan");
        getContentPane().add(jKulit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 20));

        jTampil.setText("Tampil");
        jTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTampilActionPerformed(evt);
            }
        });
        getContentPane().add(jTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });
        getContentPane().add(jReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jTutup.setText("Back");
        jTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTutupActionPerformed(evt);
            }
        });
        getContentPane().add(jTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 343, -1, -1));

        buttonGroup1.add(jYa);
        jYa.setText("Ya");
        getContentPane().add(jYa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 70, -1));

        buttonGroup1.add(jTidak);
        jTidak.setText("Tidak");
        jTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidakActionPerformed(evt);
            }
        });
        getContentPane().add(jTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WhatsApp Image 2025-09-28 at 10.42.54_b8f54e7f.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaBuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaBuahActionPerformed

    private void tWarnaBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tWarnaBuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tWarnaBuahActionPerformed

    private void tRasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRasaActionPerformed

    private void tBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBeratActionPerformed

    private void tHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHargaActionPerformed

    private void jTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTampilActionPerformed
        // TODO add your handling code here:
        Aziz_Nanas Nns = new Aziz_Nanas();
        
        if (tNamaBuah.getText().isEmpty()){
            Nns.setNama_buah("Tidak diketahui");
        } else {
            Nns.setNama_buah(tNamaBuah.getText());
        }
        if (tWarnaBuah.getText().isEmpty()){
            Nns.setWarna("Tidak diketahui");
        } else {
            Nns.setWarna(tWarnaBuah.getText());
        }
        if (tRasa.getText().isEmpty()){
            Nns.setRasa("Tidak diketahui");
        } else {
            Nns.setRasa(tNamaBuah.getText());
        }
        if (tBerat.getText().isEmpty()){
            Nns.setBerat(0);
        } else{
             Nns.setBerat(Double.parseDouble(tBerat.getText()));
        }
        if (tHarga.getText().isEmpty()){
            Nns.setHarga(0);
        }else {
            Nns.setHarga(Double.parseDouble(tHarga.getText()));
        }
        
        tNamaBuah2.setText(Nns.getNama_buah());
        tWarna2.setText(Nns.getWarna());
        tRasa1.setText(Nns.getRasa());
        tBerat1.setText(String.valueOf(Nns.getBerat()));
        tHarga1.setText(String.valueOf(Nns.getHarga()));
        
        if (jYa.isSelected()){
            tKulit2.setText("Ya, Bisa dimakan");
        }else if (jTidak.isSelected()){
            tKulit2.setText("Tidak, Kulit tidak Bisa dimakan");
        }else {
            tKulit2.setText("Tidak diketahui");
        }
    }//GEN-LAST:event_jTampilActionPerformed

    private void tNamaBuah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaBuah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaBuah2ActionPerformed

    private void tWarna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tWarna2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tWarna2ActionPerformed

    private void tRasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRasa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRasa1ActionPerformed

    private void tBerat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBerat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBerat1ActionPerformed

    private void tHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHarga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHarga1ActionPerformed

    private void tKulit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKulit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKulit2ActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        // TODO add your handling code here:
        tNamaBuah.setText(null);
        tWarnaBuah.setText(null);
        tRasa.setText(null);
        tBerat.setText(null);
        tHarga.setText(null);
        tNamaBuah2.setText(null);
        tWarna2.setText(null);
        tRasa1.setText(null);
        tBerat1.setText(null);
        tHarga1.setText(null);
        buttonGroup1.clearSelection();
        tKulit2.setText(null);
    
    }//GEN-LAST:event_jResetActionPerformed

    private void jTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTutupActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jTutupActionPerformed

    private void jTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NanasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NanasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NanasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NanasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NanasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jBerat;
    private javax.swing.JLabel jBerat1;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jHarga1;
    private javax.swing.JLabel jKulit;
    private javax.swing.JLabel jKulit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNamaBuah;
    private javax.swing.JLabel jNamaBuah1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jRasa;
    private javax.swing.JLabel jRasa1;
    private javax.swing.JButton jReset;
    private javax.swing.JButton jTampil;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jTidak;
    private javax.swing.JButton jTutup;
    private javax.swing.JLabel jWarnaBuah;
    private javax.swing.JLabel jWarnaBuah1;
    private javax.swing.JRadioButton jYa;
    private javax.swing.JTextField tBerat;
    private javax.swing.JTextField tBerat1;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tHarga1;
    private javax.swing.JTextField tKulit2;
    private javax.swing.JTextField tNamaBuah;
    private javax.swing.JTextField tNamaBuah2;
    private javax.swing.JTextField tRasa;
    private javax.swing.JTextField tRasa1;
    private javax.swing.JTextField tWarna2;
    private javax.swing.JTextField tWarnaBuah;
    // End of variables declaration//GEN-END:variables
}
