/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klmpk5_buah;

/**
 *
 * @author ASUS
 */
public class Tonikurmaframe extends javax.swing.JFrame {

    /**
     * Creates new form Tonikurmaframe
     */
    public Tonikurmaframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tNamaBuah = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tNamabuah1 = new javax.swing.JTextField();
        tberat1 = new javax.swing.JTextField();
        tharga1 = new javax.swing.JTextField();
        tkulit = new javax.swing.JTextField();
        trasa1 = new javax.swing.JTextField();
        twarna1 = new javax.swing.JTextField();
        tWarnaBuah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tRasa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tBerat = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        bTampil = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bresert = new javax.swing.JButton();
        btutup = new javax.swing.JButton();
        rTidak = new javax.swing.JRadioButton();
        rYa = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nama Buah");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        tNamaBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaBuahActionPerformed(evt);
            }
        });
        getContentPane().add(tNamaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 162, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Nama Buah");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Warna Buah");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Rasa");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Berat");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Harga per/kg");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Kulit  Bisa Dimakan");

        tNamabuah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamabuah1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(twarna1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(tkulit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(tNamabuah1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(tberat1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(trasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel12)
                                .addGap(8, 8, 8)
                                .addComponent(tharga1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(tNamabuah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tberat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8))
                            .addComponent(twarna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tkulit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(trasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addComponent(tharga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 610, 130));

        tWarnaBuah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tWarnaBuahActionPerformed(evt);
            }
        });
        getContentPane().add(tWarnaBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 162, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Rasa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 37, -1));

        tRasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRasaActionPerformed(evt);
            }
        });
        getContentPane().add(tRasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 162, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Berat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 37, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Harga per/kg");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 102, -1));

        tBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBeratActionPerformed(evt);
            }
        });
        getContentPane().add(tBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 162, -1));
        getContentPane().add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 162, -1));

        bTampil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bTampil.setText("Tampil");
        bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTampilActionPerformed(evt);
            }
        });
        getContentPane().add(bTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Kulit  Bisa Dimakan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Warna Buah");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        bresert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bresert.setText("Resert");
        bresert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresertActionPerformed(evt);
            }
        });
        getContentPane().add(bresert, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        btutup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btutup.setText("Tutup");
        btutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btutupActionPerformed(evt);
            }
        });
        getContentPane().add(btutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        buttonGroup1.add(rTidak);
        rTidak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rTidak.setText("Tidak");
        rTidak.setContentAreaFilled(false);
        rTidak.setFocusPainted(false);
        rTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTidakActionPerformed(evt);
            }
        });
        getContentPane().add(rTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 70, 30));

        buttonGroup1.add(rYa);
        rYa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rYa.setText("Ya");
        rYa.setContentAreaFilled(false);
        rYa.setFocusPainted(false);
        getContentPane().add(rYa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 50, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AKURMA.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaBuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaBuahActionPerformed

    private void tWarnaBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tWarnaBuahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tWarnaBuahActionPerformed

    private void tRasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRasaActionPerformed

    private void tBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBeratActionPerformed

    private void tNamabuah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamabuah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamabuah1ActionPerformed

    private void bTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTampilActionPerformed
        // TODO add your handling code here:
        Toni_Kurma krf = new Toni_Kurma();
        
        if (tNamaBuah.getText().isEmpty()){
            krf.setNamaBuah("Tidak Di Ketahui");
        }else{
            krf.setNamaBuah(tNamaBuah.getText());
        }
        if(tWarnaBuah.getText().isEmpty()){
             krf.setWarna("Tidak Di Ketahui");
        }else{
             krf.setWarna(tWarnaBuah.getText());
        }
        if (tRasa.getText().isEmpty()){
            krf.setRasa("Tidak Di Ketahui");
        }else{
            krf.setRasa(tRasa.getText());
        } 
        if (tBerat.getText().isEmpty()){
            krf.setBerat(0);
        }else{
            krf.setBerat(Double.parseDouble(tBerat.getText()));
        }
        if (tHarga.getText().isEmpty()){
            krf.setHarga(0);
        }else{
            krf.setHarga(Double.parseDouble(tHarga.getText()));
        }
            
        
        tNamabuah1.setText(krf.getNamaBuah());
        twarna1.setText(krf.getWarna());
        trasa1.setText(krf.getRasa());
        tberat1.setText(String.valueOf(krf.getBerat()));
        tharga1.setText(String.valueOf(krf.getHarga()));
        
        if (rYa.isSelected()){
            tkulit.setText("Ya, Bisa dimakan");
        }else if (rTidak.isSelected()) {
            tkulit.setText("Tidak, Kulit Tidak Bisa Dimakan");
        } else {
            
        }
        
    
        
    }//GEN-LAST:event_bTampilActionPerformed

    private void btutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btutupActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btutupActionPerformed

    private void bresertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresertActionPerformed
        // TODO add your handling code here:
        tNamaBuah.setText(null);
        tWarnaBuah.setText(null);
        tRasa.setText(null);
        tBerat.setText(null);
        tHarga.setText(null);
        tNamabuah1.setText(null);
        twarna1.setText(null);
        trasa1.setText(null);
        tberat1.setText(null);
        tharga1.setText(null);
        buttonGroup1.clearSelection();
        tkulit.setText(null);
    }//GEN-LAST:event_bresertActionPerformed

    private void rTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rTidakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tonikurmaframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tonikurmaframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tonikurmaframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tonikurmaframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tonikurmaframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTampil;
    private javax.swing.JButton bresert;
    private javax.swing.JButton btutup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rTidak;
    private javax.swing.JRadioButton rYa;
    private javax.swing.JTextField tBerat;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tNamaBuah;
    private javax.swing.JTextField tNamabuah1;
    private javax.swing.JTextField tRasa;
    private javax.swing.JTextField tWarnaBuah;
    private javax.swing.JTextField tberat1;
    private javax.swing.JTextField tharga1;
    private javax.swing.JTextField tkulit;
    private javax.swing.JTextField trasa1;
    private javax.swing.JTextField twarna1;
    // End of variables declaration//GEN-END:variables
}
